server:
  port: 8080
#  port: 8081

open:
  api:
    title: API-service document
    version: V1.0.0
    description: API for the blood-donation-support system
    licenseUrl: "https://example.com/license" # Replace with actual license URL
    licenseName: API License
    serversUrl: https://bds-system.azurewebsites.net
#    serversUrl: http://localhost:8081
    serversDescription: Azure Production

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    org.springdoc: DEBUG

spring:
  application:
    name: blood-donation-support-system
  datasource:
#     url: jdbc:mysql://localhost:3306/BloodDonationSupportSystem
#     username: root
#     password: 12345
    url: ${DB_URL:jdbc:mysql://hopper.proxy.rlwy.net:20492/BloodDonationSupportSystem}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:ouZMiVTcQFeORQEEGyjaCpUQnMEvqkvu}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:b60c9e7a2e251192f67c2b02773e76c8096a6e38ea49627334eddae82dc7da95}
      expiration: ${JWT_EXPIRATION:604800000} # 7 days in milliseconds
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds
